global using Serilog;
global using ILogger = Serilog.ILogger;
global using Microsoft.EntityFrameworkCore;
global using MailScanner.Shared.DB;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using MailScanner.Shared;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using System.Security.Claims;