global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Configuration.UserSecrets;
global using Microsoft.Extensions.Configuration.EnvironmentVariables;
global using Serilog;
global using ILogger = Serilog.ILogger;
global using MailScanner.Shared.DB;
global using Microsoft.EntityFrameworkCore.Design;
global using MailKit;
global using MailKit.Net.Imap;
global using MailKit.Search;
global using MimeKit;